custom:
  prod:
    db:
      password: hn4z1Yka7thUtzS

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hankhme6079@gmail.com
    password: pssgpvkubxojehlr
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true